# yaml-language-server: $schema=https://www.schemastore.org/github-action.json
---
name: Set LF line endings
description: Sets the git line ending configuration to use LF (Line Feed) only
runs:
  using: composite
  steps:
    - shell: bash
      name: "git config --global"
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
